### ISSUE TITLE
Version 3?

### ISSUE THREAD

**Issue by daveclarkit** [TobiasBuchholz/Plugin.Firebase#301]
When will version 3 be release / pushed to nuget?

**Comment by TobiasBuchholz** [comment]
Hi, I've just published all version 3.0.0 packages at nuget! 🚀🍻

**Comment by daveclarkit** [comment]
Cloudmessaging is still showing as version 2.04 so wont upgrade.....

**Comment by TobiasBuchholz** [comment]
Right, it went through now, sorry for the confusion
